apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-nexus3
  name: docker-nexus3
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: docker-nexus3
  sessionAffinity: ClientIP
  type: ClusterIP
