apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: sample-rhel7
  name: sample-rhel7
spec:
  output:
    to:
      kind: ImageStreamTag
      name: sample-rhel7:latest
  postCommit: {}
  resources:
    requests:
      cpu: 50m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: rhel7:latest
        namespace: openshift
    type: Docker
