apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /exports/nexus
    server: 1.2.3.4
  persistentVolumeReclaimPolicy: Retain
