apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
  namespace: quay-enterprise
spec:
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
  quay:
    keepConfigDeployment: true
    externalAccess:
      hostname: quay.app.example.com
    deploymentStrategy: Recreate
    imagePullSecretName: redhat-pull-secret
    skipSetup: false
