apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
  namespace: quay-enterprise
spec:
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
  quay:
    keepConfigDeployment: true
    externalAccess:
      hostname: quay.app.example.com
      tls:
        secretName: custom-quay-ssl
        termination: passthrough
    deploymentStrategy: Recreate
    imagePullSecretName: redhat-pull-secret
    skipSetup: false
    database:
      volumeSize: 10Gi
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteOnce
      persistentVolumeSize: 30Gi
      persistentVolumeStorageClassName: ocs-storagecluster-ceph-rbd
