apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-httpd
  name: httpd
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-httpd
  sessionAffinity: ClientIP
  type: ClusterIP
