apiVersion: v1                                                                                                                                                                                             [5/1097]
kind: PersistentVolumeClaim                                                                                                                                                                                        
metadata:                                                                                                                                                                                                          
  annotations:                                                                                                                                                                                                     
    pv.kubernetes.io/bind-completed: "yes"                                                                                                                                                                         
    pv.kubernetes.io/bound-by-controller: "yes"                                                                                                                                                                    
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
  finalizers:
  - kubernetes.io/pvc-protection
  name: grafana6
  namespace: openshift-monitoring
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: glusterfs-storage

